"""Prepare a local MLX-LM Mary adapter experiment bundle.

This module performs no training and no network access. It converts Mary Dataset
v1's approved chat-format SFT rows into the train/valid/test layout expected by
MLX-LM, writes a conservative LoRA/QLoRA config, and records exact base lineage
plus evaluation/stacking boundaries.

MaryBench stays held out. Ordinary chats, MemoryManager, relationship state and
provider traces remain excluded by MaryDatasetV1Exporter.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
import json
from pathlib import Path
from typing import Any

from .dataset_v1 import MaryDatasetV1Exporter
from .dataset_audit import MaryDatasetV1Auditor


@dataclass(frozen=True)
class MlxTrainingProfile:
    profile_id: str
    model: str
    upstream_base: str
    num_layers: int
    max_seq_length: int
    experiment_class: str = "development"
    minimum_train_examples: int = 8
    batch_size: int = 1
    grad_accumulation_steps: int = 4
    iters: int = 300
    learning_rate: float = 1e-5
    lora_rank: int = 8
    lora_scale: float = 16.0
    lora_dropout: float = 0.05
    grad_checkpoint: bool = True
    val_batches: int = 25
    steps_per_eval: int = 50
    save_every: int = 50

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


PROFILES: dict[str, MlxTrainingProfile] = {
    "m1-smoke": MlxTrainingProfile(
        profile_id="m1-smoke",
        model="mlx-community/Qwen3-0.6B-4bit",
        upstream_base="Qwen/Qwen3-0.6B",
        num_layers=2,
        max_seq_length=768,
        experiment_class="pipeline_smoke",
        minimum_train_examples=6,
        grad_accumulation_steps=2,
        iters=80,
        lora_rank=4,
        lora_scale=8.0,
        val_batches=10,
        steps_per_eval=20,
        save_every=20,
    ),
    "m1-light": MlxTrainingProfile(
        profile_id="m1-light",
        model="mlx-community/Qwen3-1.7B-4bit",
        upstream_base="Qwen/Qwen3-1.7B",
        num_layers=4,
        max_seq_length=1024,
        experiment_class="light_adapter_candidate",
        minimum_train_examples=12,
        grad_accumulation_steps=4,
        iters=300,
    ),
    "m1-4b": MlxTrainingProfile(
        profile_id="m1-4b",
        model="mlx-community/Qwen3-4B-Instruct-2507-4bit",
        upstream_base="Qwen/Qwen3-4B-Instruct-2507",
        num_layers=4,
        max_seq_length=1024,
        experiment_class="quality_adapter_candidate",
        minimum_train_examples=16,
        grad_accumulation_steps=4,
        iters=300,
    ),
}


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    output: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict):
            output.append(row)
    return output


def _split_for(identifier: str) -> str:
    bucket = int(sha256(identifier.encode("utf-8")).hexdigest()[:8], 16) % 100
    if bucket < 85:
        return "train"
    if bucket < 93:
        return "validation"
    return "test"


def _chat_row(row: dict[str, Any]) -> dict[str, Any] | None:
    messages = row.get("messages")
    if not isinstance(messages, list) or not messages:
        return None
    clean: list[dict[str, str]] = []
    for item in messages:
        if not isinstance(item, dict):
            return None
        role = str(item.get("role") or "").strip().lower()
        content = str(item.get("content") or "").strip()
        if role not in {"system", "user", "assistant"} or not content:
            return None
        clean.append({"role": role, "content": content})
    if not any(item["role"] == "assistant" for item in clean):
        return None
    return {"messages": clean}


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows),
        encoding="utf-8",
    )


def _yaml(profile: MlxTrainingProfile, data_dir: Path, adapter_dir: Path) -> str:
    checkpoint = "true" if profile.grad_checkpoint else "false"
    return f"""# Generated by MaryV2; review before running.
model: "{profile.model}"
train: true
fine_tune_type: lora
data: "{data_dir}"
seed: 17
num_layers: {profile.num_layers}
batch_size: {profile.batch_size}
iters: {profile.iters}
val_batches: {profile.val_batches}
learning_rate: {profile.learning_rate}
steps_per_report: 10
steps_per_eval: {profile.steps_per_eval}
grad_accumulation_steps: {profile.grad_accumulation_steps}
resume_adapter_file: null
adapter_path: "{adapter_dir}"
save_every: {profile.save_every}
test: false
test_batches: 100
max_seq_length: {profile.max_seq_length}
grad_checkpoint: {checkpoint}
lora_parameters:
  keys: ["self_attn.q_proj", "self_attn.v_proj"]
  rank: {profile.lora_rank}
  scale: {profile.lora_scale}
  dropout: {profile.lora_dropout}
"""


def prepare_mlx_bundle(
    *,
    root: str | Path,
    output_dir: str | Path,
    profile_id: str = "m1-light",
    feedback_path: str | Path | None = None,
) -> dict[str, Any]:
    profile = PROFILES.get(str(profile_id))
    if profile is None:
        raise KeyError(f"unknown MLX training profile: {profile_id}")

    root_path = Path(root).expanduser().resolve()
    output = Path(output_dir).expanduser().resolve()
    dataset_dir = output / "mary-dataset-v1"
    data_dir = output / "mlx-data"
    adapter_dir = output / "adapter"
    output.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    adapter_dir.mkdir(parents=True, exist_ok=True)

    dataset_summary = MaryDatasetV1Exporter().export(
        root=root_path,
        output_dir=dataset_dir,
        feedback_path=feedback_path,
    )
    dataset_audit = MaryDatasetV1Auditor().audit(
        dataset_dir,
        minimum_train_examples=1,
    )
    if not dataset_audit.training_ready:
        raise ValueError(
            "Mary Dataset v1 failed the structural quality gate: "
            + "; ".join(dataset_audit.blocking_issues[:8])
        )

    behavior = _load_jsonl(dataset_dir / "mary_behavior_sft.jsonl")
    feedback = _load_jsonl(dataset_dir / "explicit_feedback" / "mary_sft.jsonl")

    splits: dict[str, list[dict[str, Any]]] = {
        "train": [],
        "validation": [],
        "test": [],
    }
    source_counts = {"behavior": 0, "explicit_feedback": 0}

    for row in behavior:
        chat = _chat_row(row)
        if chat is None:
            continue
        split = str(row.get("split") or "train")
        if split not in splits:
            split = "train"
        splits[split].append(chat)
        source_counts["behavior"] += 1

    for index, row in enumerate(feedback):
        chat = _chat_row(row)
        if chat is None:
            continue
        identifier = str(row.get("feedback_id") or f"feedback-{index}")
        splits[_split_for(identifier)].append(chat)
        source_counts["explicit_feedback"] += 1

    # Small creator datasets can hash into no validation/test examples. Keep
    # training deterministic while reserving at least one non-training sample
    # when enough rows exist. Nothing is copied from MaryBench to fill gaps.
    all_rows = sum(len(items) for items in splits.values())
    if all_rows >= 5 and not splits["validation"] and len(splits["train"]) > 2:
        splits["validation"].append(splits["train"].pop())
    if all_rows >= 8 and not splits["test"] and len(splits["train"]) > 3:
        splits["test"].append(splits["train"].pop())

    if not splits["train"]:
        raise ValueError(
            "Mary Dataset has no approved behavior/feedback SFT rows; "
            "training bundle was not created."
        )

    _write_jsonl(data_dir / "train.jsonl", splits["train"])
    _write_jsonl(data_dir / "valid.jsonl", splits["validation"])
    _write_jsonl(data_dir / "test.jsonl", splits["test"])

    config_path = output / "mlx_lora_config.yaml"
    config_path.write_text(
        _yaml(profile, data_dir, adapter_dir),
        encoding="utf-8",
    )

    training_example_count = len(splits["train"])
    dataset_ready = (
        dataset_audit.training_ready
        and training_example_count >= profile.minimum_train_examples
    )
    readiness_reasons = []
    if not dataset_ready:
        readiness_reasons.append(
            "approved training rows below profile minimum "
            f"({training_example_count} < {profile.minimum_train_examples})"
        )

    manifest = {
        "version": "mary-mlx-adapter-bundle-v2",
        "profile": profile.to_dict(),
        "mary_dataset": dataset_summary.to_dict(),
        "dataset_audit": dataset_audit.to_dict(),
        "examples": {
            "train": len(splits["train"]),
            "validation": len(splits["validation"]),
            "test": len(splits["test"]),
            **source_counts,
        },
        "paths": {
            "data": str(data_dir),
            "config": str(config_path),
            "adapter": str(adapter_dir),
        },
        "training_readiness": {
            "dataset_ready": dataset_ready,
            "ready_for_training": False,
            "minimum_train_examples": profile.minimum_train_examples,
            "reasons": readiness_reasons + [
                "host/package/lineage preflight has not been run"
            ],
            "manual_creator_gate_required": True,
        },
        "run": {
            "install": 'python -m pip install "mlx-lm[train]"',
            "preflight": (
                f'python -m scripts.preflight_mary_mlx_lora --bundle "{output}"'
            ),
            "train": f'mlx_lm.lora --config "{config_path}" --mask-prompt',
            "evaluate": (
                f'mlx_lm.lora --model "{profile.model}" '
                f'--adapter-path "{adapter_dir}" --data "{data_dir}" --test'
            ),
            "generate_smoke": (
                f'mlx_lm.generate --model "{profile.model}" '
                f'--adapter-path "{adapter_dir}" '
                '--prompt "Respond naturally as Mary to: Hey, how are you doing?"'
            ),
        },
        "boundaries": {
            "training_performed": False,
            "marybench_in_training_data": False,
            "dataset_quality_gate_passed": dataset_audit.training_ready,
            "ordinary_conversation_harvested": False,
            "fictional_canon_is_lived_memory": False,
            "adapter_is_identity_authority": False,
            "exact_base_required": True,
        },
        "experiment_ladder": [
            {
                "profile_id": item.profile_id,
                "model": item.model,
                "upstream_base": item.upstream_base,
                "experiment_class": item.experiment_class,
                "minimum_train_examples": item.minimum_train_examples,
            }
            for item in PROFILES.values()
        ],
        "deployment_cautions": {
            "adapter_server_use": (
                "Do not assume an OpenAI-compatible server loaded the adapter. "
                "Verify adapter-vs-base behavior explicitly before routing Mary traffic."
            ),
            "gguf_export": (
                "Do not assume MLX GGUF export supports Qwen. Keep MLX adapter "
                "evaluation native unless a separately verified conversion path is used."
            ),
            "promotion": "No trained adapter becomes Mary identity/model authority automatically.",
        },
        "stack_matrix": {
            "required_comparisons": [
                "exact base only",
                "third-party adapter only (when exact-base compatible)",
                "Mary adapter only",
                "third-party + Mary adapter only when both target the same exact base/runtime",
            ],
            "cross_base_stacking": "forbidden",
            "promotion": (
                "blind MaryBench + identity/fiction/epistemic/tool boundary "
                "evaluation, then explicit creator decision"
            ),
        },
    }
    manifest_path = output / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
    return manifest
