name: MaryV2iOS
options:
  bundleIdPrefix: com.unbeknownstx
targets:
  MaryV2iOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.unbeknownstx.MaryV2iOS
        PRODUCT_NAME: MaryV2iOS
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Mary
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Mary
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
