name: MaryV2iOS
options:
  bundleIdPrefix: com.unbeknownstx
targets:
  MaryV2iOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.unbeknownstx.MaryV2iOS
        PRODUCT_NAME: Mary
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
